print('Apa')
print('Commit day 1')
print ('Commit day 2')
print ('Commit day 3')
print ('Commit day 3,1')
print ('Commit day 3,2')
print ('Commit day 3,3')
print ('Commit day 3,4')
print ('Commit day 4,1')
print ('Commit day 4,2')
print ('Commit day 4,3')
print ('Commit day 4,4')
print ('Commit day 4,5')
print ('Commit day 4,6')
print ('Commit day 4,7')
print ('Commit day 5,1')
print ('Commit day 5,2')
print ('Commit day 5,3')
print ('Commit day 5,4')
print ('Commit day 5,5')
print ('Commit day 5,6')
print ('Commit day 5,7')
print ('Commit day 6,1')
print ('Commit day 6,2')
print ('Commit day 6,3')
print ('Commit day 6,4')
print ('Commit day 6,5')